name: Release (beta)

on:
  push:
    branches:
      - next

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"

      - name: Setup | Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
    
      - name: Setup | Authenticate with Registry
        run: echo //npm.pkg.github.com/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup | Ensure registry access
        run: npm whoami 

      - name: Setup | Configure git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Setup | Yarn Install
        uses: bahmutov/npm-install@v1

      - name: Prepare | Lerna Version
        run: yarn lerna version --create-release github --yes

      - name: Prepare | Build
        run: yarn build

      - name: Release | Lerna Publish
        run: lerna publish from-package --yes
